version: build-{build}~branch-{branch}

clone_script:
- ps: |
    $ErrorActionPreference = "Continue"

    function gitx {
      git @args 2>&1 | % { Write-Host "$_" }
      if ($LASTEXITCODE -ne 0) {
        throw "git failed: git $args"
      }
    }

    git config --global core.autocrlf input
    git config --global gc.auto 0
    git config --global advice.detachedHead false

    $repo = $env:APPVEYOR_REPO_NAME
    $dir = $env:APPVEYOR_BUILD_FOLDER

    rm -r -fo $dir -ea SilentlyContinue

    if ($env:APPVEYOR_PULL_REQUEST_NUMBER) {
      $headRepo = $env:APPVEYOR_PULL_REQUEST_HEAD_REPO_NAME
      $headBranch = $env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH
      $headCommit = $env:APPVEYOR_PULL_REQUEST_HEAD_COMMIT

      gitx clone --depth=1 --no-tags --branch $headBranch `
        "https://github.com/$headRepo.git" $dir

      cd $dir
      gitx checkout -q -f $headCommit
    } else {
      gitx clone --depth=1 --no-tags --branch $env:APPVEYOR_REPO_BRANCH `
        "https://github.com/$repo.git" $dir

      cd $dir
      gitx checkout -q -f $env:APPVEYOR_REPO_COMMIT
    }

skip_branch_with_pr: true

install:
  - choco install winflexbison3

build_script:
  # dump some system info
  - echo  processor='%PROCESSOR_IDENTIFIER%' , processor count= %NUMBER_OF_PROCESSORS%
  - cd %APPVEYOR_BUILD_FOLDER%
  # Disable unneeded submodules for the faster build
  - git config submodule.storage/columnstore/columnstore.update none
  - git config submodule.storage/maria/libmarias3.update none
  - git config submodule.storage/rocksdb/rocksdb.update none
  - git config submodule.wsrep-lib.update none
  # Build minimal configuration
  - mkdir _build
  - cd _build
  - set BUILD_TYPE=MinSizeRel
  - set GENERATOR=-GNinja
  - call "C:\Program Files\Microsoft Visual Studio\18\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cmake -E time cmake %GENERATOR% .. -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DMYSQL_MAINTAINER_MODE=ERR -DFAST_BUILD=1 -DPLUGIN_PERFSCHEMA=NO -DPLUGIN_FEEDBACK=NO
  - set /A jobs=2*%NUMBER_OF_PROCESSORS%
  - cmake -E time cmake --build . -j %jobs% --config %BUILD_TYPE% --target minbuild

test_script:
  - set PATH=C:\Strawberry\perl\bin;%PATH%;C:\Program Files (x86)\Windows Kits\10\Debuggers\x64
  - cd %APPVEYOR_BUILD_FOLDER%\_build\mysql-test
  - set /A parallel=4*%NUMBER_OF_PROCESSORS%
  - perl mysql-test-run.pl --force --max-test-fail=10 --retry=2 --parallel=%parallel% --testcase-timeout=4 --suite=main  --skip-test-list=%APPVEYOR_BUILD_FOLDER%\win\appveyor_skip_tests.txt --mysqld=--loose-innodb-flush-log-at-trx-commit=2

skip_commits:
  files:
    - debian/
    - '**/*.sh'

branches:
  only:
    - /bb-/
    - /\d+\.\d+$/

image: Visual Studio 2026
