name: Build on Windows ARM64

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-11-arm

    steps:
      - uses: actions/checkout@v4

      - name: Show environment
        run: |
          echo Processor Architecture: $Env:PROCESSOR_ARCHITECTURE
          systeminfo
          where.exe perl.exe
      - name: Install bison
        run: |
          choco install winflexbison3

      - name: Build project
        run: |
          mkdir bld
          cd bld
          cmake .. -DWITH_SSL=bundled -DWITH_UNIT_TESTS=0
          cmake --build . --config RelWithDebinfo --verbose -- -m
          cmake --build . --config RelWithDebInfo --target win_package_zip

      - name: Test
        run: |
          $env:PATH = "C:\Strawberry\perl\bin;$env:PATH;C:\Program Files (x86)\Windows Kits\10\Debuggers\x64"
          #Calculate parallel as 4 * number of processors
          $parallel = 4 * [int]$env:NUMBER_OF_PROCESSORS
          # Run the Perl test command
          perl bld\mysql-test\mysql-test-run.pl --force --max-test-fail=10 --retry=2 --parallel=$parallel  --testcase-timeout=4 --suite=main --mysqld=--loose-innodb-flush-log-at-trx-commit=2
   